### ISSUE TITLE
Auth Library breaks hosts

### ISSUE THREAD

**Issue by vanderstack** [jspuij/BlazorWebView#11]
I've been using the webview project you stubbed out and have been enjoying it a lot. I'm attempting to add authentication so I can put in an admin dashboard, but whenever I attempt to run my application using the WPF host I get an error that it cannot find an assembly referenced by my shared project. 

I began by using your template and then adding Microsoft.Authentication.WebAssembly.Msal to my Shared project. I then added an extension method which is responsible for configuring the auth provider:
![image](https://user-images.githubusercontent.com/24641067/79299967-3a83c900-7e9a-11ea-8421-a92957081f1a.png)

Finally I wire this up in my WPF project Startup and get this message when I run the project:
![image](https://user-images.githubusercontent.com/24641067/79299915-14f6bf80-7e9a-11ea-9478-f006273cb1a3.png)

This surprises me because I'm able to use the exact same process just fine in my WebAssembly Host.

The commit where I add Auth and everything breaks is here (and very isolated)
https://github.com/vanderstack/vanderstack.github.io/commit/563983b89f2afde38acb693755e1e5e8205b6f38

Is this an issue you've run into or expect to have occur? Do you have any suggestion for what may be causing or how to resolve?

**Comment by jspuij** [comment]
Wow, you've managed to hit the single most difficult to do with BlazorWebView, which is to get auth with AD working ;-)
First the issue at hand: A number of AspNetCore packages are included in the ASP.NET Core shared framework. A normal ASP.NET Core application will just reference the framework dlls as they are included with .NET Core. They are not included with the build output, unless you do a self-containing build.
Your android app runs on Mono, and Mono does not include the AspNetCore shared framework. Especially with transitive dependencies, it seems that the build targets do not copy these assemblies. I haven't had time to look into it, but usually explicitly adding all transitive dependencies to the Android Project seems to do the job. So I'd start with adding `Microsoft.AspNetCore.Components.WebAssembly.Authentication` as nuget to the android project.

Now the second issue is that I could not get the `Microsoft.Authentication.WebAssembly.Msal` to work eventually. I'm not sure that you run into the same issue as I did, as I had a MultiTenant AAD requirement, but you will probably need a return URL as part of the authentication flow. As there is no webserver, there is no way to intercept that request and the flow fails.

I ended up implementing my own `AuthenticationStateProvider` based on Microsoft.Identity. 
https://docs.microsoft.com/en-us/aspnet/core/security/blazor/?view=aspnetcore-3.1#implement-a-custom-authenticationstateprovider
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet

I might end up writing a piece about it in the docs and open source this provider. Let me first know how it goes and whether you get MSAL to work (it would be the easiest). If you don't, I'll help you implementing your own AuthenticationStateProvider.

**Comment by vanderstack** [comment]
Unfortunately when I attempt to add the reference to my WPF project I get a yellow triangle on the dependency:
![image](https://user-images.githubusercontent.com/24641067/79404076-88a1d680-7f45-11ea-9645-590ccd0a03b8.png)

I think this is because the WPF project is referencing .net Core 3.1 which is only giving support for .net standard 2.0 while my shared project is a razor class library with support for net standard 2.1, but i'm not sure how to change this target in the WPF project.

**Comment by jspuij** [comment]
Could you share your full project file BTW? I just added the package to a WPF project and I had no issues. (Relevant Content):

```
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorWebView.Wpf" Version="0.2.0-preview4" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="3.2.0-preview3.20168.3" />
  </ItemGroup>

</Project>
```

I did notice my MSAL version is newer and corresponds with the other blazor preview assemblies though.

**Comment by jspuij** [comment]
So I upgraded some nugets and even managed to complete an authentication flow.
Code is here:
https://github.com/jspuij/vanderstack.github.io/tree/feature/auth

However, there is an issue, the return URL. The browser needs to return to an address after authentication. Normally this would be an url on a webserver that reloads blazor. However, for a number of browsers (the old and new edge mainly), the handler I build to resolve files locally has to be specified for every navigation event. When the browser tries to navigate to this uri, there is no handler, and the process stops.

There is another nasty issue and that is that the redirect uri is different per browser, so for all platforms you'd have to configure multiple inside azure. The old edge will generate a dynamic ms-stream uri every time to load blazor, so the redirect uri would be variable, which would be impossible to configure.

The only nice way to solve this, is to (temporarily for the request) run a mini webserver on localhost on a random port that intercepts the redirect_uri and picks up from there.

You can either do that, or go the System.Net.Identity route. I'll see if I can create a sample for that in the coming weeks, but don't expect something very soon.

**Comment by vanderstack** [comment]
I appreciate the prototype and advice, I don't think it should be too difficult to run a webserver for this duration. I'm imagining I can create a service that I register with the WPF startup dependency injection which can be notified when the auth flow is handing off and needs to expect a redirect, and also when the redirect has succeeded. This new service can then be responsible for starting and stopping the webserver you mentioned which would be responsible for handling any redirect and turning it into a known schema. Once it becomes a standard schema, would it be possible to integrate with the built in system for resolving a route? If so my webserver essentially just needs to serve a 403 redirect to a known address with query parameters and I can tear it down as soon as it finishes that redirect.

**Comment by vanderstack** [comment]
Could you point me to where this routing is taking place? I imagine its within the webview wpf project, and i am hopeful i can fork that as well and just add a project reference and then tinker a bit to see what I can make work?

**Comment by vanderstack** [comment]
You know, as I think more about this I feel like I question this approach. I think you made the correct decision, the WebAssembly project should use MSAL because thats what makes sense in a browser, but on a desktop it makes sense to use Identity Server and a custom provider.

I'm going to abandon this direction (although this ticket will serve as good documentation for others) and instead attempt to hook in my own provider. Thanks!

**Comment by vanderstack** [comment]
In case anyone stumbles upon this in the future, here is the prototype for how I plan to prevent any errors going forward: https://github.com/vanderstack/vanderstack.github.io/commit/7a975515950a16dfcf494a5befb06e585a4533b2

I'll follow up again once i've added a WPF Auth handler

**Comment by jspuij** [comment]
You can use mine (what I cooked up in a few hours) as an example:

https://gist.github.com/jspuij/b03a4d9bff94a12aef3c7ec0b063d140

I want to refine this, but it might get you going. Note that it uses a LocalStorageManager to store and restore state. I wrote that myself on WPF because WPF does not have secure local storage. On android and ios this is not neccessary, MSAL will automatically store and restore tokens on those platforms.

You can skip these parts for now, if you don't want to restore the authentication state on startup. Feel free to ask questions about the code.

**Comment by jspuij** [comment]
@vanderstack Did you manage to solve your auth issues? I'll close this if you did.

**Comment by vanderstack** [comment]
Yes, thank you for the guidance.
