### ISSUE TITLE
BlazorNewEdgeWebView - memory leaking, throttling

### ISSUE THREAD

**Issue by garrynewman** [jspuij/BlazorWebView#14]
In my app everything works well with the old web view, but with the BlazorNewEdgeWebView version it seems to get slower and slower as time goes on. This seems to correspond with memory usage increasing at an unexpected rate.

![image](https://user-images.githubusercontent.com/928843/82236912-bd31f500-992c-11ea-8548-bb9cdf62304b.png)

![image](https://user-images.githubusercontent.com/928843/82237115-139f3380-992d-11ea-83e9-04f591e5c002.png)

I'm not sure if this is a bug with BlazorWebView, or with the Edge stuff but thought I would mention it anyway since it doesn't seem to happen in chrome, edge, canary edge, or the old edge web view,

(currently using Edge Version 84.0.516.0)

To give an idea about what I'm doing. It's a debug console. It's getting a debug line from a socket, adding it to a list and calling StateHasChanged for each line. Around 1000 lines in it starts to get a bit crazy.

![image](https://user-images.githubusercontent.com/928843/82237366-6bd63580-992d-11ea-87aa-8de04fe525e8.png)

**Comment by jspuij** [comment]
That's interesting. Is it possible for you to share the Repo? That's easier for me to debug.

**Comment by jspuij** [comment]
The continuation chain you see is probably from the IPC calls from javascript queueing because they are not handled on the blazor thread anymore. This would suggest that the main blazor thread is blocked. But I have no idea why from these screenshots.

**Comment by garrynewman** [comment]
So yeah it's using keys, and no JS errors in the console. I would lean towards blaming the implementation, since it's working in browser - but I don't know enough about how all this works to be sure.

![image](https://user-images.githubusercontent.com/928843/82248323-d4c6a900-993f-11ea-9a0c-4b8023228a13.png)

![image](https://user-images.githubusercontent.com/928843/82248349-e3ad5b80-993f-11ea-8fb1-678a875074af.png)

**Comment by jspuij** [comment]
Some evaluatescript call is clearly hanging or taking too long... Attached is a screenshot of the sample blazor app. Clicking the button will only burst short evaluatescript calls, instead of your very long running task.

![2020-05-18 20_52_24-DevTools - app_](https://user-images.githubusercontent.com/985974/82249235-b9609b80-9949-11ea-9224-8dba20c990e1.png)

You might be able to intercept the IPC call that "hangs" by placing a brackepoint in the IPC.ts file:

![2020-05-18 20_57_53-DevTools - app_](https://user-images.githubusercontent.com/985974/82249572-502d5800-994a-11ea-9b12-ae84e80eb802.png)

**Comment by garrynewman** [comment]
So sorry - this was totally my fault, I was adding calls to StateHasChanged to an event in OnParametersSet - and didn't guard it against multiple calls.. so it was adding calls every update.

Not sure why it didn't show in browser/old view - but oh well - sorry for wasting your time.

**Comment by jspuij** [comment]
NP, glad I could help.
