### ISSUE TITLE
Setting UserdataFolder? (<programname>.WebView2)

### ISSUE THREAD

**Issue by garrynewman** [jspuij/BlazorWebView#15]
Is it possible to change the location of this folder? Are there any settings you could expose internally?

**Comment by jspuij** [comment]
I could expose them. The c++ part calls [createcorewebview2environmentwithoptions](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-488/webview2-idl#createcorewebview2environmentwithoptions), where you can specify the folders. It's not too difficult to expose them. Can you wait until the next release (it will coincide probably with the final version of Blazor webassembly)?

**Comment by garrynewman** [comment]
That would be useful - yeah can definitely wait - thank you <3
