### ISSUE TITLE
Native Preview 7 not on nuget

### ISSUE THREAD

**Issue by musictopia2** [jspuij/BlazorWebView#16]
I was trying to use the preview 7 for wpf.  However, it would not allow me to use it because it required preview 7 of the native but that never showed on nuget.

**Comment by jspuij** [comment]
@musictopia2 You were extremely unlucky that I had published the nugets around the time you looked for them. The BlazorWebView nuget will arive shortly at:

https://www.nuget.org/packages/BlazorWebView/0.2.0-preview7

Currently it is validating. I don't have control over the validation process and why the platform specific versions are published earlier than the general version.

Please try again in an hour or so. It will probably be there.

**Comment by jspuij** [comment]
![xcOa0xG 1](https://user-images.githubusercontent.com/985974/82757835-30cb7a80-9de3-11ea-8ad9-36c57c0868b8.png)

**Comment by jspuij** [comment]
I'm terribly sorry, but I guess the validation process hangs somewhere. I've created a ticket with nuget.org (that's their advice) and I will keep you posted. I might try and bump the version number tomorrow if nothing helps.

**Comment by musictopia2** [comment]
Looks like somehow the problem was still there.  Because even after 4 hours, it never showed the new version.

**Comment by jspuij** [comment]
Yeah, I bumped the version to 0.2.0-preview8 but now two packages are still validating. I’m afraid I have to wait for nuget to respond.

**Comment by musictopia2** [comment]
Looks like it finally showed the newest version now.
