### ISSUE TITLE
Uncaught Error: Cannot find module '@microsoft/dotnet-js-interop'

### ISSUE THREAD

**Issue by roceh** [jspuij/BlazorWebView#18]
The nugets work fine, but when cloning this repo and building from source it looks like it is either pulling in newer stuff for the javascript side. 

I can get it to work by editing the package.json and replacing

"@dotnet/jsinterop": "3.1.3",

with

"@microsoft/dotnet-js-interop": "5.0.0-preview.4.20257.10",

and 

import '@dotnet/jsinterop/dist/Microsoft.JSInterop';

with

import '@microsoft/dotnet-js-interop/dist/Microsoft.JSInterop';

in the src\*.ts files

I notice microsoft recently moved the js code into this renamed module.

**Comment by jspuij** [comment]
Thanks @roceh. I was still tracking the development branch for the Blazor javascript files, but it's stable by now. New nugets should be there shortly. The source should be OK as well.
