### ISSUE TITLE
[Question] Is there a way to hide the url that shows on the bottom left of the webview?

### ISSUE THREAD

**Issue by geocine** [jspuij/BlazorWebView#40]
Is there a way to hide the url that shows on the bottom left of the webview? The url shows up when you hover on a link.
![blazor](https://user-images.githubusercontent.com/507464/115659861-c19d3400-a36d-11eb-8893-0644abb0fc4c.gif)

**Comment by jspuij** [comment]
I'm afraid not. It's a security feature to make sure that users don't click a link that is strange and would redirect them to something malicious. You might try creating an onlick handler and navigating through the navigation manager.

**Comment by geocine** [comment]
Understood thanks @jspuij
